# Generated by Django 5.2.6 on 2025-10-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='category',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('corporate', 'Corporate'), ('celebration', 'Celebration'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
