# Generated by Django 5.2.6 on 2025-10-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_batch_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='zip_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='zip_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='photo',
            name='preview_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='preview_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['-created_at'], name='photos_batc_created_ca807a_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['category', '-created_at'], name='photos_batc_categor_3d8270_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['batch', 'created_at'], name='photos_phot_batch_i_146e62_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['preview_status'], name='photos_phot_preview_e09017_idx'),
        ),
    ]
