# .github/workflows/mirror.yml
name: 'mirror'
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: Configure Git
        run: git config --global --add safe.directory /github/workspace
      - name: mirror
        id: mirror
        uses: bridgelightcloud/github-mirror-action@v1
        with:
          origin: 'dotnet4to/dotnetlenses'
          GITHUB_TOKEN: ${{ secrets.MIRROR_TOKEN }}
